### ISSUE TITLE
Prevent sleeping AND lock the display

### ISSUE THREAD

**Issue by Scentle5S** [semaja2/InsomniaX#18]
Hello,

I use InsomniaX quite often and really love it.

However, there seems to be an issue when sleep is disabled AND the display is sent to sleep (or "locked", as I prefer to call it). Typical use case : you want to be sure your laptop stays awake for a long period of time (download, remote access, whatever the reason), but you also dont want anybody in the room to be able to access your computer. Solution : you use InsomniaX and the "Sleep Display Now" feature, so that you have to unlock your Mac to use it.

The problem is that locking the Mac seems to override InsomniaX's behavior, since the Mac will go to sleep after a while, similarly as when closing the lid or staying afk for too long. On the other hand, not locking the screen leads to the expected behavior, but the Mac is accessible to anybody that passes by...

Not sure if this is an issue, a feature request, or a limitation of macOS though.

Any ideas ?

Thanks

Scentle5S

**Comment by fletom** [comment]
+1

**Comment by cbarrick** [comment]
This just happened to me. Here's my use case:

I use a Jupyter to develop and run experiments on a remote machine. But the way Jupyter works, a client must always be connected. So I connect and use InsomniaX to make sure I stay connected. I was away from a power outlet, so I used "sleep display now" to save battery. But my laptop went to sleep anyway! Fortunately I wasn't afk long enough for Jupyter to timeout my connection. For my use case, I can just dim the display instead, but in general this behavior is definitely unexpected.

If the feature can't be fixed due to a restriction in macOS, perhaps the UI could be updated somehow to indicate that "sleep display now" conflicts with "disable idle sleep".

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
